### PR TITLE
Add Italian translations to RunroomSortableBehaviorBundle

### PR DESCRIPTION
**Pull request by gremo**
I'm using the RunroomSortableBehaviorBundle and it works fine. This PR adds the Italian translations.

### CODE REVIEW

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks @gremo , sorry for the delay, just saw the PR.

**Comment by gremo** [comment]
No problem @jordisala1991 , it would be nice a minor so I can delete my project temp files!

**Comment by gremo** [comment]
Can you please release a minor? Thanks!

**Comment by jordisala1991** [comment]
Sorry for the delay, here you go: https://github.com/Runroom/runroom-packages/releases/tag/0.17.2

**Pull request merged**
